algoritmo "SwitchCase"
// Função :SwitchCase
// Autor :Camila Pletsch
// Data : 01/03/2022
// Seção de Declarações
var
voto: literal
inicio
escreval("Digite seu voto:")
leia(voto)

escolha voto
caso "20"
   escreval("Você votou na Camila Pletsch")
caso "30"
   escreval("Você votou no Pernalonga")
caso "40"
   escreval("Você votou no Patolino")
outrocaso
   escreval("Voto nulo")
fimescolha
fimalgoritmo
