algoritmo "Trabalhando com Tipos"

var
palavra1, palavra2, palavra3: literal
numero1, numero2, numero3: inteiro
inicio
Escreval("Primeiro número")
leia (numero1)
Escreval("Segundo número")
leia (numero2)
Escreval("Primeira palavra")
leia (palavra1)
Escreval("Segunda palavra")
leia (palavra2)

numero3 <- numero1 + numero2
palavra3 <- palavra1 + palavra2

Escreval(numero3)
Escreval(palavra3)
fimalgoritmo
